// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

type User struct {
	UserID         string
	Mail           string
	Name           string
	Code           string
	HashedPassword string
}
