// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

type Building struct {
	BuildingID   string
	Zip          int32
	BuildingType string
	OldLevel     int32
}

type Chat struct {
	ChatID  string
	UserID1 string
	UserID2 string
	Content string
}

type Notification struct {
	NotificationID string
	UserID         string
}

type User struct {
	UserID         string
	Mail           string
	Name           string
	Code           string
	HashedPassword string
}
