// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package query

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
  chat_id, user_id_1, user_id_2, content
) VALUES (
  $1, $2, $3, $4
)
RETURNING chat_id, user_id_1, user_id_2, content
`

type CreateChatParams struct {
	ChatID  string
	UserID1 string
	UserID2 string
	Content string
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.ChatID,
		arg.UserID1,
		arg.UserID2,
		arg.Content,
	)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.UserID1,
		&i.UserID2,
		&i.Content,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  user_id, mail, name, code, hashed_password
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING user_id, mail, name, code, hashed_password
`

type CreateUserParams struct {
	UserID         string
	Mail           string
	Name           string
	Code           string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Mail,
		arg.Name,
		arg.Code,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Mail,
		&i.Name,
		&i.Code,
		&i.HashedPassword,
	)
	return i, err
}

const getChatByUserID = `-- name: GetChatByUserID :many
SELECT chat_id, user_id_1, user_id_2, content FROM chats
WHERE user_id_1 = $1 OR user_id_2 = $1
`

func (q *Queries) GetChatByUserID(ctx context.Context, userID1 string) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChatByUserID, userID1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID1,
			&i.UserID2,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, mail, name, code, hashed_password FROM users
WHERE mail = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, mail string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, mail)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Mail,
		&i.Name,
		&i.Code,
		&i.HashedPassword,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, mail, name, code, hashed_password FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Mail,
		&i.Name,
		&i.Code,
		&i.HashedPassword,
	)
	return i, err
}

const updateCode = `-- name: UpdateCode :exec
UPDATE users
  set code = $2
WHERE user_id = $1
`

type UpdateCodeParams struct {
	UserID string
	Code   string
}

func (q *Queries) UpdateCode(ctx context.Context, arg UpdateCodeParams) error {
	_, err := q.db.Exec(ctx, updateCode, arg.UserID, arg.Code)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
  set hashed_password = $2
WHERE user_id = $1
`

type UpdatePasswordParams struct {
	UserID         string
	HashedPassword string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.UserID, arg.HashedPassword)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
  set mail = $2,
  name = $3,
  hashed_password = $4
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID         string
	Mail           string
	Name           string
	HashedPassword string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Mail,
		arg.Name,
		arg.HashedPassword,
	)
	return err
}
