// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/spajam-backend/db"
	"github.com/K-Kizuku/spajam-backend/internal/app/handler"
	"github.com/K-Kizuku/spajam-backend/internal/app/repository"
	"github.com/K-Kizuku/spajam-backend/internal/app/service"
	"github.com/K-Kizuku/spajam-backend/pkg/gcp"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	queries := db.New()
	iUserRepository := repository.NewUserRepository(queries)
	client := gcp.NewStorageClient()
	iStorageRepository := repository.NewStorageRepository(client)
	iUserService := service.NewUserService(iUserRepository, iStorageRepository)
	iUserHandler := handler.NewUserHandler(iUserService)
	iChatRepository := repository.NewChatRepository(queries)
	iChatService := service.NewChatService(iChatRepository)
	iChatHandler := handler.NewChatHandler(iChatService)
	root := handler.New(iUserHandler, iChatHandler)
	return root
}
