name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ secrets.GCP_REGION }}-docker.pkg.dev"

      - name: Build and Push Docker Image with SHA and latest Tag
        run: |
          docker build -t "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_ID }}/${{ secrets.GCP_SERVICE }}:${{ github.sha }}" \
                      -t "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_ID }}/${{ secrets.GCP_SERVICE }}:latest" \
                      -f ./docker/prod/Dockerfile ./

          # Push both SHA and latest tagged images
          docker push "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_ID }}/${{ secrets.GCP_SERVICE }}:${{ github.sha }}"
          docker push "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_ID }}/${{ secrets.GCP_SERVICE }}:latest"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.GCP_SERVICE }}
          region: ${{ secrets.GCP_REGION }}
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY_ID }}/${{ secrets.GCP_SERVICE }}:${{ github.sha }}
          env_vars: |-
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }}
            MODE=prod
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            GCP_REGION=${{ secrets.GCP_REGION }}
            GCP_SERVICE=${{ secrets.GCP_SERVICE }}
            GCP_REPOSITORY_ID=${{ secrets.GCP_REPOSITORY_ID }}
            GCP_BUCKET_ID=${{ secrets.GCP_BUCKET_ID }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
